name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sql-driver: ['mysql','sqlite','postgresql']
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          tags_for_attribute ()
          {
            local ATTRIBUTE=$1
            local VERSION=$2
            local TAGS="--tag ${DOCKER_IMAGE}:${VERSION}-${ATTRIBUTE}"

            if [ "$VERSION" != "edge" ]; then
              TAGS="$TAGS --tag ${DOCKER_IMAGE}:latest-${ATTRIBUTE}"
              TAGS="$TAGS --tag ${DOCKER_IMAGE}:${ATTRIBUTE}"
            fi

            echo ${TAGS}
          }

          DOCKER_USERNAME=crazymax
          DOCKER_IMAGE=crazymax/firefox-syncserver
          DOCKER_PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
          FF_SYNCSERVER_SQL_DRIVER=${{ matrix.sql-driver }}
          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            VERSION=${TAG%-*}
          fi

          TAGS="--tag ${DOCKER_IMAGE}:${VERSION}"
          if [ "$VERSION" != "edge" ]; then
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:latest"
          fi

          TAGS="$TAGS $(tags_for_attribute ${FF_SYNCSERVER_SQL_DRIVER} ${VERSION})"

          echo ::set-output name=docker_username::${DOCKER_USERNAME}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            --build-arg FF_SYNCSERVER_SQL_DRIVER=${FF_SYNCSERVER_SQL_DRIVER} \
            ${TAGS} --file Dockerfile .
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.2.0
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build --output "type=image,push=false" ${{ steps.prepare.outputs.buildx_args }}
      -
        name: Docker Login
        if: success() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.prepare.outputs.docker_username }}" --password-stdin
      -
        name: Docker Buildx (push)
        if: success() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        run: |
          docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}
      -
        name: Docker Check Manifest
        if: success() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}
      -
        name: Clear
        if: always() && github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        run: |
          rm -f ${HOME}/.docker/config.json
